export const REVIEW_FLAG_CODES = [
  "ASSESSMENT_REQUIREMENT_UNCERTAIN",
  "INCOME_REGIME_POSSIBLY_NON_RENTAL",
  "LIMITED_TAX_CONTEXT_NEEDS_CONFIRMATION",
  "HOLIDAY_APARTMENT_INTENTION_REVIEW",
  "VACANCY_EVIDENCE_REVIEW",
  "MONUMENT_CERTIFICATE_REVIEW",
  "SPECIAL_DEPRECIATION_ELIGIBILITY_REVIEW",
  "OWNER_ROLE_REVIEW",
  "MIXED_USE_COMPONENT_SPLIT_REVIEW",
  "FORM_YEAR_SWITCH_REVIEW",
] as const;
